### ISSUE TITLE
How to set cuda device in alpha4 harvester?

### ISSUE THREAD

**Issue by liyujcx** [Chia-Network/bladebit#324]
i use the latest alpha4  harvester on windows 10, 3070 8gb gpu device,  but i don't know how to config cuda device .

![image](https://github.com/Chia-Network/bladebit/assets/129054818/9f077598-3d7e-4db4-ad0c-4836320d1842)

**Comment by liyujcx** [comment]
is there some guideline to use it...

**Comment by wallentx** [comment]
You need to update your `config.yaml` to include the latest changes under the `harvester:` section:
```yaml
  # Compressed harvesting.
  parallel_decompressers_count: 1
  # If set to 0, `decompresser_thread_count` will default to half of nproc available on the machine.
  # A non-zero number overrides this default.
  decompresser_thread_count: 0
  disable_cpu_affinity: False
  # Ignore compressed plots with compression level greater than this.
  max_compression_level_allowed: 7
  use_gpu_harvesting: False
  gpu_index: 0
  enforce_gpu_index: False
```
The `gpu_index` setting will dictate which GPU is used. You can determine the GPU index by running: `nvidia-smi --query-gpu=index,name --format=csv`
which should return info such as this:
```
index, name
0, NVIDIA RTX A4000
1, NVIDIA GTX 1080
```

I'd use `1` if I wanted to harvest using my GTX 1080, for example.
